export base_url="http://localhost:6010"
# Master Data Greeting
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Kak","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Mas","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Mba","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Bapak","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Ibu","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Om","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Tante","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Kang","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Bang","Description" : ""}'
curl --location --request POST "{$base_url}/greeting" --header 'Content-Type: application/json' --data-raw '{"GreetingId" : "Ustad","Description" : ""}'

# Master Data Interest
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Reseller","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Marketer/Affiliate","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Kuliner","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Fashion","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Jasa","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Desain","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Ecourse","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Kecantikan","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Keluarga","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Kesehatan","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Gaya hidup","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Olahraga","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Aksesoris","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Teknologi","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Freelence","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Desain","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Seni","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Marketing","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Produksi","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Keuangan","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Treveling","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Pariwisata","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Pendidikan","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Pertanian/Perkebunan","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Peternakan/perikanan","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Multimedia","Description" : ""}'
curl --location --request POST "{$base_url}/interest" --header 'Content-Type: application/json' --data-raw '{"InterestId" : "Komunitas Sosial","Description" : ""}'

# Master data Settings
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "FEE_AFFILIATE","Value" : "0"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "CREDIT_CONTACT","Value" : "150"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "CS_CONTACT","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "CS_CONTACT_TOPUP","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "FEE_AFFILIATE_CREDIT","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "CS_MESSAGE_TOPUP","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "TEMPLATE_SHARE","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "VERSION_APP","Value" : "1"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "UPDATED_REQUIRED","Value" : "1"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "URL_BANTUAN","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "URL_KEBIJAKAN_PRIVASI","Value" : "null"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "LIMIT_WITHDRAW","Value" : "10000"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "ADD_CREDIT_AFTER_REGISTER","Value" : "0"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "FEE_CLICK_ADS_FEED","Value" : "0"}'
curl --location --request POST "{$base_url}/settings" --header 'Content-Type: application/json' --data-raw '{"SettingsId" : "CLICK_ADS_MESSAGE","Value" : ""}'

curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":1,"Province":"Bali"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":2,"Province":"Bangka Belitung"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":3,"Province":"Banten"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":4,"Province":"Bengkulu"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":5,"Province":"DI Yogyakarta"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":6,"Province":"DKI Jakarta"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":7,"Province":"Gorontalo"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":8,"Province":"Jambi"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":9,"Province":"Jawa Barat"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":10,"Province":"Jawa Tengah"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":11,"Province":"Jawa Timur"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":12,"Province":"Kalimantan Barat"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":13,"Province":"Kalimantan Selatan"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":14,"Province":"Kalimantan Tengah"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":15,"Province":"Kalimantan Timur"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":16,"Province":"Kalimantan Utara"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":17,"Province":"Kepulauan Riau"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":18,"Province":"Lampung"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":19,"Province":"Maluku"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":20,"Province":"Maluku Utara"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":21,"Province":"Nanggroe Aceh Darussalam (NAD)"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":22,"Province":"Nusa Tenggara Barat (NTB)"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":23,"Province":"Nusa Tenggara Timur (NTT)"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":24,"Province":"Papua"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":25,"Province":"Papua Barat"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":26,"Province":"Riau"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":27,"Province":"Sulawesi Barat"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":28,"Province":"Sulawesi Selatan"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":29,"Province":"Sulawesi Tengah"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":30,"Province":"Sulawesi Tenggara"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":31,"Province":"Sulawesi Utara"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":32,"Province":"Sumatera Barat"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":33,"Province":"Sumatera Selatan"}'
curl --location --request POST "{$base_url}/province" --header 'Content-Type: application/json' --data-raw '{"ProvinceId":34,"Province":"Sumatera Utara"}'

curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":408,"ProvinceId":28,"City":"Sidenreng Rappang/Rapang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":401,"ProvinceId":19,"City":"Seram Bagian Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":1,"ProvinceId":21,"City":"Aceh Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":14,"ProvinceId":19,"City":"Ambon"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":74,"ProvinceId":11,"City":"Kabupaten Blitar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":331,"ProvinceId":3,"City":"Pandeglang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":353,"ProvinceId":34,"City":"Pematang Siantar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":377,"ProvinceId":10,"City":"Purworejo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":89,"ProvinceId":15,"City":"Bontang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":90,"ProvinceId":24,"City":"Boven Digoel"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":91,"ProvinceId":10,"City":"Boyolali"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":92,"ProvinceId":10,"City":"Brebes"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":93,"ProvinceId":32,"City":"Bukittinggi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":94,"ProvinceId":1,"City":"Buleleng"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":95,"ProvinceId":28,"City":"Bulukumba"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":96,"ProvinceId":16,"City":"Bulungan (Bulongan)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":97,"ProvinceId":8,"City":"Bungo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":98,"ProvinceId":29,"City":"Buol"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":270,"ProvinceId":23,"City":"Manggarai Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":435,"ProvinceId":23,"City":"Sumba Barat Daya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":406,"ProvinceId":26,"City":"Siak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":146,"ProvinceId":34,"City":"Humbang Hasundutan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":147,"ProvinceId":26,"City":"Indragiri Hilir"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":148,"ProvinceId":26,"City":"Indragiri Hulu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":149,"ProvinceId":9,"City":"Indramayu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":150,"ProvinceId":24,"City":"Intan Jaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":151,"ProvinceId":6,"City":"Jakarta Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":152,"ProvinceId":6,"City":"Jakarta Pusat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":153,"ProvinceId":6,"City":"Jakarta Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":154,"ProvinceId":6,"City":"Jakarta Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":300,"ProvinceId":21,"City":"Nagan Raya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":365,"ProvinceId":12,"City":"Pontianak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":293,"ProvinceId":8,"City":"Muaro Jambi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":99,"ProvinceId":19,"City":"Buru"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":100,"ProvinceId":19,"City":"Buru Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":101,"ProvinceId":30,"City":"Buton"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":102,"ProvinceId":30,"City":"Buton Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":103,"ProvinceId":9,"City":"Ciamis"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":104,"ProvinceId":9,"City":"Cianjur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":105,"ProvinceId":10,"City":"Cilacap"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":106,"ProvinceId":3,"City":"Cilegon"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":107,"ProvinceId":9,"City":"Cimahi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":108,"ProvinceId":9,"City":"Kabupaten Cirebon"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":109,"ProvinceId":9,"City":"Kota Cirebon"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":110,"ProvinceId":34,"City":"Dairi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":111,"ProvinceId":24,"City":"Deiyai (Deliyai)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":112,"ProvinceId":34,"City":"Deli Serdang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":113,"ProvinceId":10,"City":"Demak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":114,"ProvinceId":1,"City":"Denpasar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":115,"ProvinceId":9,"City":"Depok"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":116,"ProvinceId":32,"City":"Dharmasraya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":117,"ProvinceId":24,"City":"Dogiyai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":118,"ProvinceId":22,"City":"Dompu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":119,"ProvinceId":29,"City":"Donggala"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":120,"ProvinceId":26,"City":"Dumai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":121,"ProvinceId":33,"City":"Empat Lawang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":122,"ProvinceId":23,"City":"Ende"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":123,"ProvinceId":28,"City":"Enrekang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":124,"ProvinceId":25,"City":"Fakfak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":125,"ProvinceId":23,"City":"Flores Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":126,"ProvinceId":9,"City":"Garut"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":127,"ProvinceId":21,"City":"Gayo Lues"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":128,"ProvinceId":1,"City":"Gianyar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":129,"ProvinceId":7,"City":"Kota Gorontalo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":130,"ProvinceId":7,"City":"Kabupaten Gorontalo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":131,"ProvinceId":7,"City":"Gorontalo Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":132,"ProvinceId":28,"City":"Gowa"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":133,"ProvinceId":11,"City":"Gresik"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":134,"ProvinceId":10,"City":"Grobogan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":135,"ProvinceId":5,"City":"Gunung Kidul"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":136,"ProvinceId":14,"City":"Gunung Mas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":137,"ProvinceId":34,"City":"Gunungsitoli"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":138,"ProvinceId":20,"City":"Halmahera Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":139,"ProvinceId":20,"City":"Halmahera Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":140,"ProvinceId":20,"City":"Halmahera Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":141,"ProvinceId":20,"City":"Halmahera Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":142,"ProvinceId":20,"City":"Halmahera Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":143,"ProvinceId":13,"City":"Hulu Sungai Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":144,"ProvinceId":13,"City":"Hulu Sungai Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":145,"ProvinceId":13,"City":"Hulu Sungai Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":155,"ProvinceId":6,"City":"Jakarta Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":156,"ProvinceId":8,"City":"Jambi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":157,"ProvinceId":24,"City":"Kota Jayapura"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":158,"ProvinceId":24,"City":"Kabupaten Jayapura"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":76,"ProvinceId":10,"City":"Blora"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":77,"ProvinceId":7,"City":"Boalemo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":78,"ProvinceId":9,"City":"Kota Bogor"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":79,"ProvinceId":9,"City":"Kabupaten Bogor"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":80,"ProvinceId":11,"City":"Bojonegoro"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":82,"ProvinceId":31,"City":"Bolaang Mongondow Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":83,"ProvinceId":31,"City":"Bolaang Mongondow Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":84,"ProvinceId":31,"City":"Bolaang Mongondow Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":85,"ProvinceId":30,"City":"Bombana"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":86,"ProvinceId":11,"City":"Bondowoso"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":160,"ProvinceId":11,"City":"Jember"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":161,"ProvinceId":1,"City":"Jembrana"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":162,"ProvinceId":28,"City":"Jeneponto"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":163,"ProvinceId":10,"City":"Jepara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":164,"ProvinceId":11,"City":"Jombang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":165,"ProvinceId":25,"City":"Kaimana"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":166,"ProvinceId":26,"City":"Kampar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":167,"ProvinceId":14,"City":"Kapuas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":168,"ProvinceId":12,"City":"Kapuas Hulu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":169,"ProvinceId":10,"City":"Karanganyar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":170,"ProvinceId":1,"City":"Karangasem"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":171,"ProvinceId":9,"City":"Karawang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":172,"ProvinceId":17,"City":"Karimun"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":173,"ProvinceId":34,"City":"Karo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":174,"ProvinceId":14,"City":"Katingan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":175,"ProvinceId":4,"City":"Kaur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":176,"ProvinceId":12,"City":"Kayong Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":177,"ProvinceId":10,"City":"Kebumen"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":178,"ProvinceId":11,"City":"Kota Kediri"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":179,"ProvinceId":11,"City":"Kabupaten Kediri"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":180,"ProvinceId":24,"City":"Keerom"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":181,"ProvinceId":10,"City":"Kendal"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":182,"ProvinceId":30,"City":"Kendari"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":183,"ProvinceId":4,"City":"Kepahiang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":184,"ProvinceId":17,"City":"Kepulauan Anambas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":185,"ProvinceId":19,"City":"Kepulauan Aru"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":186,"ProvinceId":32,"City":"Kepulauan Mentawai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":187,"ProvinceId":26,"City":"Kepulauan Meranti"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":188,"ProvinceId":31,"City":"Kepulauan Sangihe"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":189,"ProvinceId":6,"City":"Kepulauan Seribu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":190,"ProvinceId":31,"City":"Kepulauan Siau Tagulandang Biaro (Sitaro)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":191,"ProvinceId":20,"City":"Kepulauan Sula"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":194,"ProvinceId":8,"City":"Kerinci"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":195,"ProvinceId":12,"City":"Ketapang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":196,"ProvinceId":10,"City":"Klaten"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":197,"ProvinceId":1,"City":"Klungkung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":198,"ProvinceId":30,"City":"Kolaka"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":199,"ProvinceId":30,"City":"Kolaka Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":200,"ProvinceId":30,"City":"Konawe"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":201,"ProvinceId":30,"City":"Konawe Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":202,"ProvinceId":30,"City":"Konawe Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":203,"ProvinceId":13,"City":"Kotabaru"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":204,"ProvinceId":31,"City":"Kotamobagu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":205,"ProvinceId":14,"City":"Kotawaringin Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":206,"ProvinceId":14,"City":"Kotawaringin Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":207,"ProvinceId":26,"City":"Kuantan Singingi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":208,"ProvinceId":12,"City":"Kubu Raya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":75,"ProvinceId":11,"City":"Kota Blitar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":209,"ProvinceId":10,"City":"Kudus"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":210,"ProvinceId":5,"City":"Kulon Progo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":211,"ProvinceId":9,"City":"Kuningan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":212,"ProvinceId":23,"City":"Kota Kupang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":213,"ProvinceId":23,"City":"Kabupaten Kupang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":214,"ProvinceId":15,"City":"Kutai Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":215,"ProvinceId":15,"City":"Kutai Kartanegara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":216,"ProvinceId":15,"City":"Kutai Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":217,"ProvinceId":34,"City":"Labuhan Batu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":218,"ProvinceId":34,"City":"Labuhan Batu Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":219,"ProvinceId":34,"City":"Labuhan Batu Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":220,"ProvinceId":33,"City":"Lahat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":221,"ProvinceId":14,"City":"Lamandau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":222,"ProvinceId":11,"City":"Lamongan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":223,"ProvinceId":18,"City":"Lampung Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":224,"ProvinceId":18,"City":"Lampung Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":225,"ProvinceId":18,"City":"Lampung Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":227,"ProvinceId":18,"City":"Lampung Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":228,"ProvinceId":12,"City":"Landak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":229,"ProvinceId":34,"City":"Langkat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":230,"ProvinceId":21,"City":"Langsa"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":231,"ProvinceId":24,"City":"Lanny Jaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":232,"ProvinceId":3,"City":"Lebak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":233,"ProvinceId":4,"City":"Lebong"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":234,"ProvinceId":23,"City":"Lembata"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":235,"ProvinceId":21,"City":"Lhokseumawe"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":236,"ProvinceId":32,"City":"Lima Puluh Koto/Kota"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":237,"ProvinceId":17,"City":"Lingga"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":238,"ProvinceId":22,"City":"Lombok Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":239,"ProvinceId":22,"City":"Lombok Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":240,"ProvinceId":22,"City":"Lombok Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":243,"ProvinceId":11,"City":"Lumajang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":244,"ProvinceId":28,"City":"Luwu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":245,"ProvinceId":28,"City":"Luwu Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":246,"ProvinceId":28,"City":"Luwu Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":247,"ProvinceId":11,"City":"Kota Madiun"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":248,"ProvinceId":11,"City":"Kabupaten Madiun"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":249,"ProvinceId":10,"City":"Kota Magelang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":250,"ProvinceId":10,"City":"Kabupaten Magelang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":251,"ProvinceId":11,"City":"Magetan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":252,"ProvinceId":9,"City":"Majalengka"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":253,"ProvinceId":27,"City":"Majene"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":254,"ProvinceId":28,"City":"Makassar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":255,"ProvinceId":11,"City":"Kota Malang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":256,"ProvinceId":11,"City":"Kabupaten Malang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":257,"ProvinceId":16,"City":"Malinau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":258,"ProvinceId":19,"City":"Maluku Barat Daya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":259,"ProvinceId":19,"City":"Maluku Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":260,"ProvinceId":19,"City":"Maluku Tenggara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":261,"ProvinceId":19,"City":"Maluku Tenggara Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":262,"ProvinceId":27,"City":"Mamasa"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":263,"ProvinceId":24,"City":"Mamberamo Raya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":264,"ProvinceId":24,"City":"Mamberamo Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":265,"ProvinceId":27,"City":"Mamuju"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":266,"ProvinceId":27,"City":"Mamuju Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":267,"ProvinceId":31,"City":"Manado"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":269,"ProvinceId":23,"City":"Manggarai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":271,"ProvinceId":23,"City":"Manggarai Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":272,"ProvinceId":25,"City":"Manokwari"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":273,"ProvinceId":25,"City":"Manokwari Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":274,"ProvinceId":24,"City":"Mappi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":275,"ProvinceId":28,"City":"Maros"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":276,"ProvinceId":22,"City":"Mataram"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":277,"ProvinceId":25,"City":"Maybrat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":278,"ProvinceId":34,"City":"Medan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":279,"ProvinceId":12,"City":"Melawi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":280,"ProvinceId":8,"City":"Merangin"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":281,"ProvinceId":24,"City":"Merauke"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":282,"ProvinceId":18,"City":"Mesuji"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":283,"ProvinceId":18,"City":"Metro"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":284,"ProvinceId":24,"City":"Mimika"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":285,"ProvinceId":31,"City":"Minahasa"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":286,"ProvinceId":31,"City":"Minahasa Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":287,"ProvinceId":31,"City":"Minahasa Tenggara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":288,"ProvinceId":31,"City":"Minahasa Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":289,"ProvinceId":11,"City":"Kota Mojokerto"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":290,"ProvinceId":11,"City":"Kabupaten Mojokerto"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":291,"ProvinceId":29,"City":"Morowali"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":292,"ProvinceId":33,"City":"Muara Enim"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":468,"ProvinceId":9,"City":"Kabupaten Tasikmalaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":81,"ProvinceId":31,"City":"Bolaang Mongondow (Bolmong)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":294,"ProvinceId":4,"City":"Muko Muko"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":295,"ProvinceId":30,"City":"Muna"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":297,"ProvinceId":33,"City":"Musi Banyuasin"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":298,"ProvinceId":33,"City":"Musi Rawas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":299,"ProvinceId":24,"City":"Nabire"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":301,"ProvinceId":23,"City":"Nagekeo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":302,"ProvinceId":17,"City":"Natuna"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":303,"ProvinceId":24,"City":"Nduga"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":304,"ProvinceId":23,"City":"Ngada"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":305,"ProvinceId":11,"City":"Nganjuk"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":306,"ProvinceId":11,"City":"Ngawi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":307,"ProvinceId":34,"City":"Nias"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":308,"ProvinceId":34,"City":"Nias Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":309,"ProvinceId":34,"City":"Nias Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":310,"ProvinceId":34,"City":"Nias Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":311,"ProvinceId":16,"City":"Nunukan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":312,"ProvinceId":33,"City":"Ogan Ilir"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":313,"ProvinceId":33,"City":"Ogan Komering Ilir"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":314,"ProvinceId":33,"City":"Ogan Komering Ulu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":315,"ProvinceId":33,"City":"Ogan Komering Ulu Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":316,"ProvinceId":33,"City":"Ogan Komering Ulu Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":317,"ProvinceId":11,"City":"Pacitan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":318,"ProvinceId":32,"City":"Padang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":319,"ProvinceId":34,"City":"Padang Lawas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":320,"ProvinceId":34,"City":"Padang Lawas Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":321,"ProvinceId":32,"City":"Padang Panjang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":392,"ProvinceId":24,"City":"Sarmi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":404,"ProvinceId":34,"City":"Serdang Bedagai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":403,"ProvinceId":3,"City":"Kabupaten Serang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":322,"ProvinceId":32,"City":"Padang Pariaman"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":405,"ProvinceId":14,"City":"Seruyan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":323,"ProvinceId":34,"City":"Padang Sidempuan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":324,"ProvinceId":33,"City":"Pagar Alam"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":325,"ProvinceId":34,"City":"Pakpak Bharat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":326,"ProvinceId":14,"City":"Palangka Raya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":327,"ProvinceId":33,"City":"Palembang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":328,"ProvinceId":28,"City":"Palopo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":329,"ProvinceId":29,"City":"Palu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":330,"ProvinceId":11,"City":"Pamekasan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":332,"ProvinceId":9,"City":"Pangandaran"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":333,"ProvinceId":28,"City":"Pangkajene Kepulauan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":334,"ProvinceId":2,"City":"Pangkal Pinang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":335,"ProvinceId":24,"City":"Paniai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":336,"ProvinceId":28,"City":"Parepare"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":337,"ProvinceId":32,"City":"Pariaman"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":338,"ProvinceId":29,"City":"Parigi Moutong"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":339,"ProvinceId":32,"City":"Pasaman"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":340,"ProvinceId":32,"City":"Pasaman Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":341,"ProvinceId":15,"City":"Paser"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":342,"ProvinceId":11,"City":"Kota Pasuruan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":343,"ProvinceId":11,"City":"Kabupaten Pasuruan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":344,"ProvinceId":10,"City":"Pati"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":345,"ProvinceId":32,"City":"Payakumbuh"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":346,"ProvinceId":25,"City":"Pegunungan Arfak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":347,"ProvinceId":24,"City":"Pegunungan Bintang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":348,"ProvinceId":10,"City":"Kota Pekalongan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":349,"ProvinceId":10,"City":"Kabupaten Pekalongan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":350,"ProvinceId":26,"City":"Pekanbaru"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":351,"ProvinceId":26,"City":"Pelalawan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":352,"ProvinceId":10,"City":"Pemalang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":354,"ProvinceId":15,"City":"Penajam Paser Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":355,"ProvinceId":18,"City":"Pesawaran"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":356,"ProvinceId":18,"City":"Pesisir Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":357,"ProvinceId":32,"City":"Pesisir Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":358,"ProvinceId":21,"City":"Pidie"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":359,"ProvinceId":21,"City":"Pidie Jaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":360,"ProvinceId":28,"City":"Pinrang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":361,"ProvinceId":7,"City":"Pohuwato"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":362,"ProvinceId":27,"City":"Polewali Mandar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":363,"ProvinceId":11,"City":"Ponorogo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":364,"ProvinceId":12,"City":"Kota Pontianak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":366,"ProvinceId":29,"City":"Poso"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":367,"ProvinceId":33,"City":"Prabumulih"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":368,"ProvinceId":18,"City":"Pringsewu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":369,"ProvinceId":11,"City":"Kota Probolinggo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":370,"ProvinceId":11,"City":"Kabupaten Probolinggo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":488,"ProvinceId":19,"City":"Tual"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":192,"ProvinceId":31,"City":"Kepulauan Talaud"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":193,"ProvinceId":24,"City":"Kepulauan Yapen (Yapen Waropen)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":226,"ProvinceId":18,"City":"Lampung Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":241,"ProvinceId":22,"City":"Lombok Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":268,"ProvinceId":34,"City":"Mandailing Natal"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":296,"ProvinceId":14,"City":"Murung Raya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":371,"ProvinceId":14,"City":"Pulang Pisau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":372,"ProvinceId":20,"City":"Pulau Morotai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":373,"ProvinceId":24,"City":"Puncak"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":374,"ProvinceId":24,"City":"Puncak Jaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":375,"ProvinceId":10,"City":"Purbalingga"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":376,"ProvinceId":9,"City":"Purwakarta"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":378,"ProvinceId":25,"City":"Raja Ampat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":410,"ProvinceId":29,"City":"Sigi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":379,"ProvinceId":4,"City":"Rejang Lebong"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":380,"ProvinceId":10,"City":"Rembang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":381,"ProvinceId":26,"City":"Rokan Hilir"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":382,"ProvinceId":26,"City":"Rokan Hulu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":383,"ProvinceId":23,"City":"Rote Ndao"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":384,"ProvinceId":21,"City":"Sabang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":385,"ProvinceId":23,"City":"Sabu Raijua"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":386,"ProvinceId":10,"City":"Salatiga"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":387,"ProvinceId":15,"City":"Samarinda"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":388,"ProvinceId":12,"City":"Sambas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":389,"ProvinceId":34,"City":"Samosir"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":390,"ProvinceId":11,"City":"Sampang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":391,"ProvinceId":12,"City":"Sanggau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":393,"ProvinceId":8,"City":"Sarolangun"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":394,"ProvinceId":32,"City":"Sawah Lunto"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":395,"ProvinceId":12,"City":"Sekadau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":396,"ProvinceId":28,"City":"Selayar (Kepulauan Selayar)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":397,"ProvinceId":4,"City":"Seluma"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":398,"ProvinceId":10,"City":"Kota Semarang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":399,"ProvinceId":10,"City":"Kabupaten Semarang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":400,"ProvinceId":19,"City":"Seram Bagian Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":2,"ProvinceId":21,"City":"Aceh Barat Daya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":3,"ProvinceId":21,"City":"Aceh Besar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":4,"ProvinceId":21,"City":"Aceh Jaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":87,"ProvinceId":28,"City":"Bone"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":88,"ProvinceId":7,"City":"Bone Bolango"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":159,"ProvinceId":24,"City":"Jayawijaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":242,"ProvinceId":33,"City":"Lubuk Linggau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":407,"ProvinceId":34,"City":"Sibolga"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":411,"ProvinceId":32,"City":"Sijunjung (Sawah Lunto Sijunjung)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":412,"ProvinceId":23,"City":"Sikka"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":413,"ProvinceId":34,"City":"Simalungun"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":414,"ProvinceId":21,"City":"Simeulue"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":415,"ProvinceId":12,"City":"Singkawang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":416,"ProvinceId":28,"City":"Sinjai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":417,"ProvinceId":12,"City":"Sintang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":418,"ProvinceId":11,"City":"Situbondo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":419,"ProvinceId":5,"City":"Sleman"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":420,"ProvinceId":32,"City":"Kota Solok"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":421,"ProvinceId":32,"City":"Kabupaten Solok"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":422,"ProvinceId":32,"City":"Solok Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":423,"ProvinceId":28,"City":"Soppeng"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":424,"ProvinceId":25,"City":"Kota Sorong"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":425,"ProvinceId":25,"City":"Kabupaten Sorong"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":426,"ProvinceId":25,"City":"Sorong Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":427,"ProvinceId":10,"City":"Sragen"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":428,"ProvinceId":9,"City":"Subang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":429,"ProvinceId":21,"City":"Subulussalam"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":430,"ProvinceId":9,"City":"Kota Sukabumi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":431,"ProvinceId":9,"City":"Kabupaten Sukabumi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":432,"ProvinceId":14,"City":"Sukamara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":433,"ProvinceId":10,"City":"Sukoharjo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":434,"ProvinceId":23,"City":"Sumba Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":436,"ProvinceId":23,"City":"Sumba Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":437,"ProvinceId":23,"City":"Sumba Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":438,"ProvinceId":22,"City":"Sumbawa"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":439,"ProvinceId":22,"City":"Sumbawa Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":440,"ProvinceId":9,"City":"Sumedang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":441,"ProvinceId":11,"City":"Sumenep"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":442,"ProvinceId":8,"City":"Sungaipenuh"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":443,"ProvinceId":24,"City":"Supiori"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":444,"ProvinceId":11,"City":"Surabaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":445,"ProvinceId":10,"City":"Surakarta (Solo)"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":446,"ProvinceId":13,"City":"Tabalong"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":447,"ProvinceId":1,"City":"Tabanan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":448,"ProvinceId":28,"City":"Takalar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":449,"ProvinceId":25,"City":"Tambrauw"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":450,"ProvinceId":16,"City":"Tana Tidung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":451,"ProvinceId":28,"City":"Tana Toraja"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":452,"ProvinceId":13,"City":"Tanah Bumbu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":453,"ProvinceId":32,"City":"Tanah Datar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":454,"ProvinceId":13,"City":"Tanah Laut"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":455,"ProvinceId":3,"City":"Kota Tangerang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":456,"ProvinceId":3,"City":"Kabupaten Tangerang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":457,"ProvinceId":3,"City":"Tangerang Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":458,"ProvinceId":18,"City":"Tanggamus"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":459,"ProvinceId":34,"City":"Tanjung Balai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":402,"ProvinceId":3,"City":"Kota Serang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":460,"ProvinceId":8,"City":"Tanjung Jabung Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":461,"ProvinceId":8,"City":"Tanjung Jabung Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":462,"ProvinceId":17,"City":"Tanjung Pinang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":463,"ProvinceId":34,"City":"Tapanuli Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":464,"ProvinceId":34,"City":"Tapanuli Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":465,"ProvinceId":34,"City":"Tapanuli Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":466,"ProvinceId":13,"City":"Tapin"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":467,"ProvinceId":16,"City":"Tarakan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":469,"ProvinceId":9,"City":"Kota Tasikmalaya"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":470,"ProvinceId":34,"City":"Tebing Tinggi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":471,"ProvinceId":8,"City":"Tebo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":472,"ProvinceId":10,"City":"Kota Tegal"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":473,"ProvinceId":10,"City":"Kabupaten Tegal"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":474,"ProvinceId":25,"City":"Teluk Bintuni"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":475,"ProvinceId":25,"City":"Teluk Wondama"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":476,"ProvinceId":10,"City":"Temanggung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":477,"ProvinceId":20,"City":"Ternate"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":478,"ProvinceId":20,"City":"Tidore Kepulauan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":479,"ProvinceId":23,"City":"Timor Tengah Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":480,"ProvinceId":23,"City":"Timor Tengah Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":481,"ProvinceId":34,"City":"Toba Samosir"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":482,"ProvinceId":29,"City":"Tojo Una-Una"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":483,"ProvinceId":29,"City":"Toli-Toli"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":484,"ProvinceId":24,"City":"Tolikara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":485,"ProvinceId":31,"City":"Tomohon"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":486,"ProvinceId":28,"City":"Toraja Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":487,"ProvinceId":11,"City":"Trenggalek"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":5,"ProvinceId":21,"City":"Aceh Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":6,"ProvinceId":21,"City":"Aceh Singkil"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":7,"ProvinceId":21,"City":"Aceh Tamiang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":8,"ProvinceId":21,"City":"Aceh Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":9,"ProvinceId":21,"City":"Aceh Tenggara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":10,"ProvinceId":21,"City":"Aceh Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":11,"ProvinceId":21,"City":"Aceh Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":13,"ProvinceId":23,"City":"Alor"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":15,"ProvinceId":34,"City":"Asahan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":16,"ProvinceId":24,"City":"Asmat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":17,"ProvinceId":1,"City":"Badung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":18,"ProvinceId":13,"City":"Balangan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":19,"ProvinceId":15,"City":"Balikpapan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":20,"ProvinceId":21,"City":"Banda Aceh"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":21,"ProvinceId":18,"City":"Bandar Lampung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":22,"ProvinceId":9,"City":"Kota Bandung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":23,"ProvinceId":9,"City":"Kabupaten Bandung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":24,"ProvinceId":9,"City":"Bandung Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":25,"ProvinceId":29,"City":"Banggai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":26,"ProvinceId":29,"City":"Banggai Kepulauan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":27,"ProvinceId":2,"City":"Bangka"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":28,"ProvinceId":2,"City":"Bangka Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":29,"ProvinceId":2,"City":"Bangka Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":30,"ProvinceId":2,"City":"Bangka Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":31,"ProvinceId":11,"City":"Bangkalan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":32,"ProvinceId":1,"City":"Bangli"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":33,"ProvinceId":13,"City":"Kota Banjar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":34,"ProvinceId":9,"City":"Kabupaten Banjar"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":35,"ProvinceId":13,"City":"Banjarbaru"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":36,"ProvinceId":13,"City":"Banjarmasin"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":37,"ProvinceId":10,"City":"Banjarnegara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":38,"ProvinceId":28,"City":"Bantaeng"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":39,"ProvinceId":5,"City":"Bantul"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":40,"ProvinceId":33,"City":"Banyuasin"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":41,"ProvinceId":10,"City":"Banyumas"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":42,"ProvinceId":11,"City":"Banyuwangi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":43,"ProvinceId":13,"City":"Barito Kuala"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":44,"ProvinceId":14,"City":"Barito Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":45,"ProvinceId":14,"City":"Barito Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":46,"ProvinceId":14,"City":"Barito Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":47,"ProvinceId":28,"City":"Barru"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":48,"ProvinceId":17,"City":"Batam"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":49,"ProvinceId":10,"City":"Batang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":50,"ProvinceId":8,"City":"Batang Hari"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":51,"ProvinceId":11,"City":"Batu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":52,"ProvinceId":34,"City":"Batu Bara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":53,"ProvinceId":30,"City":"Bau-Bau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":54,"ProvinceId":9,"City":"Kota Bekasi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":409,"ProvinceId":11,"City":"Sidoarjo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":12,"ProvinceId":32,"City":"Agam"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":55,"ProvinceId":9,"City":"Kabupaten Bekasi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":56,"ProvinceId":2,"City":"Belitung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":57,"ProvinceId":2,"City":"Belitung Timur"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":58,"ProvinceId":23,"City":"Belu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":59,"ProvinceId":21,"City":"Bener Meriah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":60,"ProvinceId":26,"City":"Bengkalis"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":61,"ProvinceId":12,"City":"Bengkayang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":62,"ProvinceId":4,"City":"Bengkulu"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":63,"ProvinceId":4,"City":"Bengkulu Selatan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":64,"ProvinceId":4,"City":"Bengkulu Tengah"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":65,"ProvinceId":4,"City":"Bengkulu Utara"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":66,"ProvinceId":15,"City":"Berau"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":67,"ProvinceId":24,"City":"Biak Numfor"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":68,"ProvinceId":22,"City":"Kota Bima"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":69,"ProvinceId":22,"City":"Kabupaten Bima"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":70,"ProvinceId":34,"City":"Binjai"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":71,"ProvinceId":17,"City":"Bintan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":72,"ProvinceId":21,"City":"Bireuen"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":73,"ProvinceId":31,"City":"Bitung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":489,"ProvinceId":11,"City":"Tuban"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":490,"ProvinceId":18,"City":"Tulang Bawang"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":491,"ProvinceId":18,"City":"Tulang Bawang Barat"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":492,"ProvinceId":11,"City":"Tulungagung"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":493,"ProvinceId":28,"City":"Wajo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":494,"ProvinceId":30,"City":"Wakatobi"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":495,"ProvinceId":24,"City":"Waropen"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":496,"ProvinceId":18,"City":"Way Kanan"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":497,"ProvinceId":10,"City":"Wonogiri"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":498,"ProvinceId":10,"City":"Wonosobo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":499,"ProvinceId":24,"City":"Yahukimo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":500,"ProvinceId":24,"City":"Yalimo"}'
curl --location --request POST "{$base_url}/city" --header 'Content-Type: application/json' --data-raw '{"CityId":501,"ProvinceId":5,"City":"Yogyakarta"}'
