version: '3'
services:
  api_contacthub:
    container_name: api_contact_hub
    image: api_contact_hub
    command: bash -c "python3 /app/app.py"
    environment:
      TZ: Asia/Jakarta
    ports:
      - "6010:80"
    volumes:
      - .:/app
networks:
    default:
        external:
            name: contacthub_net